use_frameworks!

platform :ios, '9.0'

target 'WebP_Example' do
  pod 'WebP', :path => '../'

  target 'WebP_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
